### ISSUE TITLE
The QuoteAnnotationPlugin (demo) causes text not to wrap

### ISSUE THREAD

**Issue by tombogle** [ubsicap/paratext_demo_plugins#12]
I haven't yet figured out if this is a problem in the demo plugin or in Paratext itself, but I'm guessing the latter, since it doesn't seem like a plugin that is just trying to apply annotations could/should cause Paratext to lay out the data differently beyond what is needed to apply the highlighting.

**Comment by FoolRunning** [comment]
Can you give a screenshot of what you are seeing? I wasn't able to reproduce what I think you are describing.

**Comment by tombogle** [comment]
Without annotations (note: no horizontal scroll bar)
![image](https://user-images.githubusercontent.com/4229598/185651785-8ae44307-d295-487c-ba15-21e803992f44.png)

With annotations:
![image](https://user-images.githubusercontent.com/4229598/185651940-16d206b5-993b-4a88-a019-afa7842a1058.png)

**Comment by tombogle** [comment]
Plugin is generating bazillions of zero-width annotations, and (due to a seemingly unfixable deficiency in Paratext/Firefox) wrapping is suppressed between annotation spans. As a separate improvement to Paratext itself, if a plugin generates zero-width annotations with no icon, Paratext will supply an error icon and tool tip text to indicate that the annotation is invalid.

**Comment by tombogle** [comment]
Fixed by https://github.com/ubsicap/paratext_demo_plugins/pull/13
