### ISSUE TITLE
Error being generated with the latest Paratext build (9.2.102.19)

### ISSUE THREAD

**Issue by GeoDirk** [ubsicap/paratext_demo_plugins#15]
Hey Guys,

With the latest version of Paratext, we started to get this error message being thrown by the application;

![image](https://user-images.githubusercontent.com/1356726/186772198-2cd2e3e9-20f9-4bb1-bc33-c0009159c7a8.png)

It only happens when we start the plugin from the menu (menu item is off the Tools menu of a project).  If Paratext starts up with the plugin already enabled, it doesn't trigger the error.  I'm going to attach a zip of our current build of our plugin so you can hopefully reproduce and track down what error is getting thrown internally inside Paratext.

[ClearDashboardWebApiPlugin.zip](https://github.com/ubsicap/paratext_demo_plugins/files/9428368/ClearDashboardWebApiPlugin.zip)

**Comment by FoolRunning** [comment]
Here's what I see:
```
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'd:\temp'.'
 	mscorlib.dll!System.IO.__Error.WinIOError(int errorCode, string maybeFullPath)	Unknown
 	mscorlib.dll!System.IO.Directory.InternalCreateDirectory(string fullPath, string path, object dirSecurityObj, bool checkHost)	Unknown
 	mscorlib.dll!System.IO.Directory.InternalCreateDirectoryHelper(string path, bool checkHost)	Unknown
 	Serilog.Sinks.File.dll!Serilog.Sinks.File.FileSink.FileSink(string path, Serilog.Formatting.ITextFormatter textFormatter, long? fileSizeLimitBytes, System.Text.Encoding encoding, bool buffered, Serilog.Sinks.File.FileLifecycleHooks hooks)	Unknown
 	Serilog.Sinks.File.dll!Serilog.Sinks.File.RollingFileSink.OpenFile(System.DateTime now, int? minSequence)	Unknown
 	Serilog.Sinks.File.dll!Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo(System.DateTime now, bool nextSequence)	Unknown
 	Serilog.Sinks.File.dll!Serilog.Sinks.File.RollingFileSink.Emit(Serilog.Events.LogEvent logEvent)	Unknown
 	Serilog.dll!Serilog.Core.Sinks.SafeAggregateSink.Emit(Serilog.Events.LogEvent logEvent)	Unknown
 	Serilog.dll!Serilog.Core.Logger.Write(Serilog.Events.LogEventLevel level, System.Exception exception, string messageTemplate, object[] propertyValues)	Unknown
 	Serilog.dll!Serilog.Core.Logger.Write(Serilog.Events.LogEventLevel level, string messageTemplate)	Unknown
 	Serilog.dll!Serilog.Log.Information(string messageTemplate)	Unknown
 	ClearDashboard.WebApiParatextPlugin.ptxplg!ClearDashboard.WebApiParatextPlugin.MainWindow.AppendText(System.Drawing.Color color, string message) Line 466	C#
 	ClearDashboard.WebApiParatextPlugin.ptxplg!ClearDashboard.WebApiParatextPlugin.MainWindow.OnAddedToParent(Paratext.PluginInterfaces.IPluginChildWindow parent, Paratext.PluginInterfaces.IWindowPluginHost host, string state) Line 104	C#

```

For future reference, you should be able to see this in the Paratext log file by holding down Shift and clicking on **Paratext Main Menu > Support and development > View trace log** and scroll to the bottom of the log to see any exception stack traces that might have been generated.

**Comment by GeoDirk** [comment]
@FoolRunning Thanks for the log and the tip of how to get there.  Clearly we have a hard coded path in there.
