### ISSUE TITLE
Adding a default constructor causes "missing default constructor" error

### ISSUE THREAD

**Issue by steve-pence** [ubsicap/paratext_demo_plugins#16]
I tried to add a default (parameterless) constructor to my plugin class. No matter what functionality I added to the constructor. Paratext displays the following in a dialog on startup; "Plugin "ScriptureMapLabeler.PluginMenu" failed to load: Missing default constructor." 
I was able to reproduce this by adding an empty constructor to ParatextHelloWorldMenuPlugin.HelloWorldMenuPlugin.cs consisting of the following single line of code:
HelloWorldMenuPlugin() { }

Please understand, I'm not complaining about the inability to add an EMPTY constructor.  The problem is that no matter what code I put inside, e.g. I'd like to add a trace listener, I get the same issue. I'm attaching my modified version of the demo code.

[HelloWorldMenuPlugin .cs.txt](https://github.com/ubsicap/paratext_demo_plugins/files/9533981/HelloWorldMenuPlugin.cs.txt)
.

**Comment by jwickberg** [comment]
Hello Steve,

The problem with your Hello World example is that you have made the default
constructor private (that is the default scope when you don't specify it).
This then hides the compiler generated public constructor that Paratext
uses to create an instance of the plugin.

If you make the constructor public, it should work.

John

**Comment by steve-pence** [comment]
Confirming that making the constructor public resolved the issue.
