### ISSUE TITLE
Paratext fails to subscribe to IPluginAnnotationSource.AnnotationsChanged

### ISSUE THREAD

**Issue by tombogle** [ubsicap/paratext_demo_plugins#17]
It appears that Paratext's PluginAnnotationSource class fails to subscribe to the plugin's AnnotationsChanged event, which should cause it to raise it's own AnnotationsChanged event so that the annotations are refreshed. (At least I think that's how it's supposed to work.)

**Comment by FoolRunning** [comment]
Good catch. 
This should be fixed in the next version of Paratext 9.2 that gets released (looks like it will be 9.2.102.21).
