### ISSUE TITLE
getting "Plugin cannot directly access internal Paratext files" trying to write plain text as plugin data 

### ISSUE THREAD

**Issue by steve-pence** [ubsicap/paratext_demo_plugins#22]
Trying to write one line to a plain text file...
internal static void TryWritingPLuginData(IPluginObject thisRun, IParatextChildState state)
        {
            string message = "Hello from foo!";
            TWPDsavedDataId = "foo.txt";
            Trace.WriteLine("MyTrace says: Asking for lock...");
            IWriteLock writelock = state.Project.RequestWriteLock(thisRun, TWPDRollback, TWPDsavedDataId);
            Trace.WriteLine("MyTrace says: Got the lock, now for the write...");
            state.Project.PutPluginData(writelock, thisRun, TWPDsavedDataId, writer => writer.Write(message) );
        }

MyTrace says: Asking for lock...
Paratext.exe Information: 0 : ### Exception reported on line:  HandleException at offset 107 in file:line:column F:\ParatextPatchBuilds\Paratext_9.2_Patches\ParatextBase\ParatextErrorReporter.cs:97:17

Paratext.exe Information: 0 : ###  Paratext.PluginInterfaces.ParatextPluginException: Plugin cannot directly access internal Paratext files
Parameter name: fileName ---> System.ArgumentException: Plugin cannot directly access internal Paratext files
Parameter name: fileName

The error is being returned by the call to get the lock.  Obviously, I'm missing something. I didn't see anything in the api about "telling" Paratext I want to start saving my own data in this file. It seems like you just pick a file name and start using it. 

I looked through ref plugin F, which uses an xml file, but the idea is the same, 

Thanks for any suggestions,

Steve

**Comment by FoolRunning** [comment]
This is definitely a bug that I will write up. Paratext wants to own all files with a .txt extension (also applies to .map, .sty, .tec, .ttf, .vrs, .kb2, .adj, .ini, .cct, .dic, .fil, .ssf, .lds, .ldml, .ptwc2). 
Although it's not ideal, you can work around it until it's fixed by choosing a different extension for your file.

**Comment by steve-pence** [comment]
Hi Tim,

Thanks so much for your prompt reply and your work on this. The workaround
is certainly simple enough.

Blessings,

Steve



Steve Pence
Publishing Coordinator
SIL Southern Africa
Fish Hoek, Cape Town
South Africa

skype steve.pence
WhatsApp +27 83 304 6658
GMT/UTC +2

**Comment by steve-pence** [comment]
Hi again, Tim,

I switched to .dat, and that worked. But I've noticed another oddity. There
is a doubled up directory name in the path to my file foo.dat
C:\My Paratext 9 Projects\pcmDBL\pluginData\
ScriptureMapLabeler\ScriptureMapLabeler\foo.dat.

I noticed the same issue when I ran two of your demo plugins that also save
plugin data:
C:\My Paratext 9 Projects\pcmDBL\pluginData\
ProjectTextEditorPlugin\ProjectTextEditorPlugin\savedTextData.xml
C:\My Paratext 9 Projects\pcmDBL\pluginData\
ReferencePluginF\ReferencePluginF\PluginFData.xml

I suspect that is not your intent.
Should I write it up as another issue, or can you include it in this?

Thanks,
Steve

**Comment by FoolRunning** [comment]
That is by-design since you can have multiple plugins (**.ptxplg** files) in the same folder. The plugin data path is the name of the plugin folder followed by the name of the plugin **.ptxplg** file.

**Comment by steve-pence** [comment]
Great. I had no idea multiple plugins were possible in a single directory.

Thanks again,
Steve
