### ISSUE TITLE
Plugin Single Instance

### ISSUE THREAD

**Issue by GeoDirk** [ubsicap/paratext_demo_plugins#24]
We have a desire to only have one of our plugin windows open at a time.  Is there any API mechanism by which Paratext knows to only open one instance at a time?

**Comment by tombogle** [comment]
No. that is something your plugin would have to handle itself. See [Transcelerator](https://github.com/sillsdev/Transcelerator/blob/master/Transcelerator/TxlPlugin.cs) for a good example of how to do this. (In Transcelerator's case, it allows only one per project, but you could do something similar (only easier) if your plugin is not project-specific and you wanted to allow only one instance.

**Comment by GeoDirk** [comment]
@tombogle That is what I figured.  No worries, we had a backup plan of handling it.

Thanks!
