### ISSUE TITLE
Plugin not loaded

### ISSUE THREAD

**Issue by adamb924** [ubsicap/paratext_demo_plugins#25]
I can build `ParatextHelloWorldMenuPlugin` and `ReferencePluginD` in Visual Studio 2019 without errors (targeting .NET Framework 4.8, x64). When I copy the DLLs and rename them as indicated in the [build instructions](https://github.com/ubsicap/paratext_demo_plugins/wiki/Building-a-Plugin), and run Paratext, it creates a `AddIns.store` file in the plugins folder, but the plugin doesn't appear otherwise (e.g., in a menu). Is there a way to debug this?

**Comment by FoolRunning** [comment]
The Paratext log file could have some more information. You can access it easily by holding Shift and clicking on the **Main Paratext Menu > Support and development > View trace log**.

**Comment by tombogle** [comment]
It might be intuitive/obvious, but I just realized that the documentation doesn't actually state this: The menu entry for ReferencePluginD (which is a IParatextScrTextAnnotationPlugin and therefore implements PluginAnnotationMenuEntries) should be added to the bottom of each project's View menu. Thought I'd point that out in case you're looking for the menu item in the wrong place. (This is not the default location for other plugin menu items.)

**Comment by adamb924** [comment]
@FoolRunning Yes that was the problem. I see it in the documentation now, “After building a project to generate the plugin, it is necessary to copy the .dll file (and .pdb file if you are interested in debugging) to a folder for that plugin under the plugins folder for the Paratext installation.” — An example path for the plugin, as you gave in this answer, would make the documentation that much clearer. @tombogle Thank you for suggesting that; I think that was part of the ReferencePluginD documentation).
