### ISSUE TITLE
Syntax clarification on PutUSFM

### ISSUE THREAD

**Issue by steve-pence** [ubsicap/paratext_demo_plugins#27]
Hi,
I'm trying to understand how to call PutUSFM at the granularity of a chapter.  Quoting the documentation ...

> void PutUSFM([IWriteLock](https://github.com/ubsicap/paratext_demo_plugins/wiki/IWriteLock) writeLock, string usfmData, int bookNum)

> Requests Paratext to write (and overwrite if existing) data for a chapter or book represented by the given USFM data.

It says "chapter or book" but the only parameter I see is bookNum. If I want to replace only one chapter, how do I tell the API which chapter?

Thanks for any clarification.

Steve

**Comment by tombogle** [comment]
If the USFM is one chapter's worth of data (starts with a a single \c marker), it will add/replace just that one chapter.

**Comment by steve-pence** [comment]
Thanks, Tom. That's very helpful. A note about that in documentation might be appropriate, otherwise usage at the chapter level is a bit obscure.

**Comment by FoolRunning** [comment]
In the [PutUSFM documentation](https://github.com/ubsicap/paratext_demo_plugins/wiki/IProject#putusfm), it does say the following:
> usfmData - Data representing either a single chapter in the given book or the entire book. If replacing an entire book, the given data must have content for all existing chapters...
