### ISSUE TITLE
User has changed scripture event?

### ISSUE THREAD

**Issue by GeoDirk** [ubsicap/paratext_demo_plugins#3]
I'm not seeing anything in the API which allows us to be notified when a user modifies the scripture text.  Are there any plans of having something like that put into the API where we can get an event raised that shows us at least the BBBCCCVVV of the changed verse in real-time?

**Comment by tombogle** [comment]
See IProject.ScriptureDataChanged

**Comment by tombogle** [comment]
Changes are only registered/reported down to a chapter level, not individual verses.

**Comment by GeoDirk** [comment]
Ah, so there it is...  Appreciate the pointer to where it was hiding!
