### ISSUE TITLE
Versification object creation

### ISSUE THREAD

**Issue by GeoDirk** [ubsicap/paratext_demo_plugins#30]
In the API, we can read the `project.Versification` object.  But the interface is insufficient to create a new versification object if the versification has been customized.  Right now the project versification comes back as:

```
project.Versification
{CARS\custom.vrs}
    IsCustomized: true
    Type: RussianProtestant
    Versification: {CARS\custom.vrs}
```

How is it possible to create a new versification object that includes all of the above?  Using libpalaso or other open SIL library is a fine option too.

**Comment by FoolRunning** [comment]
I don't understand what you're after. Versifications can only be customized through a project in Paratext (with the **custom.vrs** file). The versification (including the customization) is given when you get the versification from the project.

**Comment by GeoDirk** [comment]
We figured this out through the Palaso library unit tests.  Closing.
