### ISSUE TITLE
OnClose / OnLeave Events

### ISSUE THREAD

**Issue by GeoDirk** [ubsicap/paratext_demo_plugins#32]
Hey Team,

There doesn't appear to be an `OnClose()` type event that we can tap into - an event for when the window is physically closed by the user.   There is an `OnLeave()` event which behaves more like lost focus where it is triggered when the user leaves our panel window and goes to another.  And oddly enough, the header for that override has a description that it is closing:

![image](https://user-images.githubusercontent.com/1356726/233395242-4c5e2bc5-1534-4225-84b2-e979b0eae1c1.png)

Is there really not a OnClose/OnClosing event that we can tap into?

**Comment by FoolRunning** [comment]
There is a [WindowClosing event](https://github.com/ubsicap/paratext_demo_plugins/wiki/IPluginChildWindow#windowclosing) on the child window you should be able to access.

**Comment by GeoDirk** [comment]
Ah...perfect thanks!
