### ISSUE TITLE
GetAllProjects()  Additional Information

### ISSUE THREAD

**Issue by GeoDirk** [ubsicap/paratext_demo_plugins#9]
While GetAllProjects() works as advertised, for NLP we need a couple of more things that are still hidden so we can correctly versification the text.  Specifically, we need access to the "usfm.sty" and "custom.vrs" file data.  Both of these are used by Damian's Machine in the versification/tokenization process.

**Comment by tombogle** [comment]
Not sure what you mean by "correctly versification the text". I'm guessing you mean something like "parse the text by verse"? The plugin interfaces already have the ability to supply the plugin with tokens that should be able to be correctly interpreted by the plugin via the normal versification conversion process so that the plugin con work in whatever versification it needs even if the project uses a different/custom one.

**Comment by GeoDirk** [comment]
@tombogle So if I'm reading in the USFM from one of the resources, it already is in it's own correct versification pattern (e.g., Russian Orthodox).  Then I could use the VerseRef.ChangeVersification() to get a reference back to the ScrVers.Original.  Do I have that right?

**Comment by FoolRunning** [comment]
@GeoDirk, What information is needed from the **usfm.sty** file? You can get most of the styling information from [IProject.ScriptureMarkerInformation](https://github.com/ubsicap/paratext_demo_plugins/wiki/IProject#scripturemarkerinformation). There is some documentation missing (that I'm planning on adding now) describing that the property can return [IParagraphMarkerInfo](https://github.com/ubsicap/paratext_demo_plugins/wiki/IParagraphMarkerInfo), [ICharacterMarkerInfo](https://github.com/ubsicap/paratext_demo_plugins/wiki/ICharacterMarkerInfo), and [INoteMarkerInfo](https://github.com/ubsicap/paratext_demo_plugins/wiki/INoteMarkerInfo) which will give you the styling information for each marker type. 

Again, I'm not sure what data you need specifically from **custom.vrs**, but you can get versification data for a project from [IProject.Versification](https://github.com/ubsicap/paratext_demo_plugins/wiki/IProject#versification). Going from one versification to another can be done via [IVersification.ChangeVersification](https://github.com/ubsicap/paratext_demo_plugins/wiki/IVersification#changeversification) or [IVerseRef.ChangeVersification](https://github.com/ubsicap/paratext_demo_plugins/wiki/IVerseRef#changeversification).

**Comment by GeoDirk** [comment]
@FoolRunning @tombogle I think I can get everything I need from the above then.  As I mentioned above, we are using Machine's toolset for taking USFM and doing the tokenization step and Damian's function uses those two file inputs.  But seems like we could regenerate them from the above information or override his function.

Thanks!

**Comment by FoolRunning** [comment]
I'm not sure what tokenization you're doing, but there is [IProject.GetUSFMTokens](https://github.com/ubsicap/paratext_demo_plugins/wiki/IProject#getusfmtokens) which returns the project USFM as tokens already.

**Comment by GeoDirk** [comment]
In our case tokenization is where we breaking apart the verse text into all its subparts for SMT input.

**Comment by GeoDirk** [comment]
In our case tokenization is where we breaking apart the verse text into all its subparts for SMT input.
